name: .NET Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      working-directory: practice2025
      run: dotnet restore

    - name: Build main project
      working-directory: practice2025/task01
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      working-directory: practice2025
      run: dotnet test task01Tests/task01Tests.csproj --no-build --logger "console;verbosity=normal"