name: .NET Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      working-directory: practice2025
      run: dotnet restore

    - name: Build only main project (task01)
      working-directory: practice2025/task01
      run: dotnet build --no-restore --configuration Debug

    - name: Run tests (task01Tests)
      working-directory: practice2025
      run: dotnet test task01Tests/task01Tests.csproj --logger "console;verbosity=normal"