name: .NET Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore practice2025/practice2025.sln

    - name: Test
      run: dotnet test practice2025/practice2025.sln --logger "console;verbosity=normal"